# Generated by Django 5.2.8 on 2025-11-17 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parto',
            name='fecha_parto',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='parto',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partos', to='api.madre'),
        ),
        migrations.AlterField(
            model_name='reciennacido',
            name='parto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rn', to='api.parto'),
        ),
    ]
