# Generated by Django 5.2.8 on 2025-11-23 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reciennacido_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12, unique=True),
        ),
    ]
