"""
Django settings for Proyecto project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-e$*0kj7^^%#jv=84mhrchf)wr965g^iwhuqs7ymka3a988m!e5'

DEBUG = True

ALLOWED_HOSTS = []


# ------------------------------
#     APLICACIONES INSTALADAS
# ------------------------------

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',   # Necesario para API
    'api',              # Tu aplicación
]


# ------------------------------
#     MIDDLEWARE
# ------------------------------

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Proyecto.urls'


# ------------------------------
#     TEMPLATES (CORREGIDO)
# ------------------------------

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Aquí agregamos la carpeta donde está base.html
        'DIRS': [BASE_DIR / 'Proyecto' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Proyecto.wsgi.application'


# ------------------------------
#           BASE DE DATOS
# ------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ------------------------------
#   VALIDACIÓN DE CONTRASEÑAS
# ------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# ------------------------------
#      INTERNACIONALIZACIÓN
# ------------------------------

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'

USE_I18N = True
USE_TZ = True


# ------------------------------
#      ARCHIVOS ESTÁTICOS
# ------------------------------

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "Proyecto/static"
]


STATIC_ROOT = BASE_DIR / "staticfiles"




DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
